simulation_params:
  dt: 0.001
  num_steps: 1000
  gamma: 1.0
  mass: 1.0
  beta: 1.0                  # 1 / kBT

training_params:
  alpha: 1.0
  alpha_1: 10.0
  alpha_2: 0.0
  learning_rate: 0.1
  batch_size: 10000
  training_iterations: 100

protocol_params:
  num_coefficient: 10
  a_endpoints: [10.0, 10.0]
  b_endpoints: [20.0, 20.0]
  c_endpoints: [0.0, 0.0]
  